GRANT USAGE ON SCHEMA public TO pulsar_app;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public TO pulsar_app;
GRANT USAGE, SELECT, UPDATE
  ON ALL SEQUENCES IN SCHEMA public TO pulsar_app;

ALTER DEFAULT PRIVILEGES FOR ROLE pulsar_zero IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pulsar_app;
ALTER DEFAULT PRIVILEGES FOR ROLE pulsar_zero IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO pulsar_app;
