name: Deploy

on:
  push:
    branches:
      - main
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Docker
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t tasks-tracker:$GITHUB_SHA .
          docker tag tasks-tracker:$GITHUB_SHA your-docker-repo/tasks-tracker:latest
          docker push your-docker-repo/tasks-tracker:latest
